### ISSUE TITLE
Public WebAPI Access - no need for WebSession

### ISSUE THREAD

**Issue by CodeCoded** [falahati/SDroid#2]
Loving this library - very well written, great understanding of C#!

I was looking to get a users inventory for a logged in user on the client, and whilst I intend to use this for bots (more learning exercise), I noticed you have all the models for the UserInventory  so thought why no re-use, but....I am forced to use web session object. 

Be great if you extended the API so that can make public Steam web api calls that don't require authentication or a web session object. All the plumbing is there and would make this library even more powerful!

**Comment by falahati** [comment]
Hey, thank you. 

What are you trying to do exactly? Get public inventory information of a user?

**Comment by falahati** [comment]
`SteamWebAccess.GetGuest()` gives you guest access to be used with other classes.

````c#
var steamId = new SteamID(/*STEAMID HERE*/);
var inventory = await UserInventory.GetInventory(SteamWebAccess.GetGuest(), steamId);
```

**Comment by CodeCoded** [comment]
Thanks for getting back so quick - And yep- that was the answer. 

Sorry - I should have seen that. I recall reading in the docs, but got too lost up in the code and Steam websites, and jumped onto GitHub too soon! 

Much awesome
