### ISSUE TITLE
HTTP/HTTPS redirect error

### ISSUE THREAD

**Issue by kadavuar** [falahati/SDroid#3]
Hi, I'm trying to use your library to write a program that automatically send and accepts trade offers. But when I try to get mobile confirmations I get this error on this line:
var confirmations = await authenticator.FetchConfirmations();
Error eng:
Cannot handle redirect from HTTP/HTTPS protocols to other dissimilar ones.

Other functions work good.

![error](https://user-images.githubusercontent.com/106839741/171937195-489a1758-44fd-4852-8eb1-7789e5d4723a.png)

**Comment by falahati** [comment]
Please share your code.
This library is being used in multiple bots in productions right now so it should be ok.

the error message seems like a problem with steam trying to force you to log in again. (altho we have a separate exception type for OAuth expiration). Usually, this can be solved by getting a new session using the OAuth refresh token stored in the MA file. What you can do to see if this is the root of the problem before trying to code your way to automate it is to use SDA to log in again (select account, choice login from the menu) and then use the newly updated MA file. if this problem goes away it means that you need to write a piece of code to automatic refreshing the session and if required, automate relogin.

**Comment by kadavuar** [comment]
Hello, refreshing token really helped. It's stupid that I didn't immediately think about it, thank you so much.
